### ISSUE TITLE
ark cannot open 7z

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/KDE-utils-appimage#1]
./KDE_Utils_suite-22.12.3+5.142-x86_64.AppImage ark
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/91205045-27e7-4773-9ccf-67c49f237475)

./KDE_Utils_suite-22.12.3+5.142-x86_64.AppImage ark sd.7z not working 
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/c3d62b3f-b07a-45b3-aa79-ebb61bd60fea)

![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/653a4253-a427-4eb0-886a-33b407965e0f)

**Comment by newyorkthink** [comment]
it always show 无法找到压缩包 “/tmp/.mount_KDE_Ut3AoT9w/usr/share/kxmlgui5/ark”。

**Comment by ivan-hc** [comment]
this is really strange, p7zip and p7zip-full are already included... I'll try to include	p7zip-rar too into the next commit

I move this issue into https://github.com/ivan-hc/KDE-utils-appimage/issues/2
