### ISSUE TITLE
zsh: segmentation fault  KDE-utils kwalletmanager5

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/KDE-utils-appimage#2]
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/5074d5bf-6134-46bf-bdf9-89bebd67e9d3)

note: THE KDE-utils is your appimage , i rename

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/KDE-utils-appimage/commit/dc6173e5ca7461a855e5ef276734d4c7c5e3c4d1 solves the issue, also improved the integration with the host and the usability of all the apps

Wait the end of the GH action before you download it.
